-- Database Scoped Configurations
-- WARNING: These settings are hardware-specific (e.g., MAXDOP)
-- Review and adjust for target environment before applying

-- Configuration: ACCELERATED_PLAN_FORCING
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET ACCELERATED_PLAN_FORCING = ON;
GO

-- Configuration: ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY = OFF;
GO

-- Configuration: BATCH_MODE_ADAPTIVE_JOINS
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ADAPTIVE_JOINS = ON;
GO

-- Configuration: BATCH_MODE_MEMORY_GRANT_FEEDBACK
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO

-- Configuration: BATCH_MODE_ON_ROWSTORE
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
GO

-- Configuration: CE_FEEDBACK
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET CE_FEEDBACK = ON;
GO

-- Configuration: DEFERRED_COMPILATION_TV
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = ON;
GO

-- Configuration: DOP_FEEDBACK
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET DOP_FEEDBACK = OFF;
GO

-- Configuration: DW_COMPATIBILITY_LEVEL
-- Current Value: 0
ALTER DATABASE SCOPED CONFIGURATION SET DW_COMPATIBILITY_LEVEL = 0;
GO

-- Configuration: ELEVATE_ONLINE
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_ONLINE = OFF;
GO

-- Configuration: ELEVATE_RESUMABLE
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_RESUMABLE = OFF;
GO

-- Configuration: EXEC_QUERY_STATS_FOR_SCALAR_FUNCTIONS
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET EXEC_QUERY_STATS_FOR_SCALAR_FUNCTIONS = ON;
GO

-- Configuration: FORCE_SHOWPLAN_RUNTIME_PARAMETER_COLLECTION
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET FORCE_SHOWPLAN_RUNTIME_PARAMETER_COLLECTION = OFF;
GO

-- Configuration: GLOBAL_TEMPORARY_TABLE_AUTO_DROP
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET GLOBAL_TEMPORARY_TABLE_AUTO_DROP = ON;
GO

-- Configuration: IDENTITY_CACHE
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

-- Configuration: INTERLEAVED_EXECUTION_TVF
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF = ON;
GO

-- Configuration: ISOLATE_SECURITY_POLICY_CARDINALITY
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET ISOLATE_SECURITY_POLICY_CARDINALITY = OFF;
GO

-- Configuration: LAST_QUERY_PLAN_STATS
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET LAST_QUERY_PLAN_STATS = OFF;
GO

-- Configuration: LEDGER_DIGEST_STORAGE_ENDPOINT
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET LEDGER_DIGEST_STORAGE_ENDPOINT = OFF;
GO

-- Configuration: LEGACY_CARDINALITY_ESTIMATION
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

-- Configuration: LIGHTWEIGHT_QUERY_PROFILING
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET LIGHTWEIGHT_QUERY_PROFILING = ON;
GO

-- Configuration: MAXDOP
-- Current Value: 4
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 4;
GO

-- Configuration: MEMORY_GRANT_FEEDBACK_PERCENTILE_GRANT
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERCENTILE_GRANT = ON;
GO

-- Configuration: MEMORY_GRANT_FEEDBACK_PERSISTENCE
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERSISTENCE = ON;
GO

-- Configuration: OPTIMIZED_PLAN_FORCING
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZED_PLAN_FORCING = ON;
GO

-- Configuration: OPTIMIZE_FOR_AD_HOC_WORKLOADS
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZE_FOR_AD_HOC_WORKLOADS = OFF;
GO

-- Configuration: PARAMETER_SENSITIVE_PLAN_OPTIMIZATION
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SENSITIVE_PLAN_OPTIMIZATION = ON;
GO

-- Configuration: PARAMETER_SNIFFING
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

-- Configuration: PAUSED_RESUMABLE_INDEX_ABORT_DURATION_MINUTES
-- Current Value: 1440
ALTER DATABASE SCOPED CONFIGURATION SET PAUSED_RESUMABLE_INDEX_ABORT_DURATION_MINUTES = 1440;
GO

-- Configuration: QUERY_OPTIMIZER_HOTFIXES
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = ON;
GO

-- Configuration: ROW_MODE_MEMORY_GRANT_FEEDBACK
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO

-- Configuration: TSQL_SCALAR_UDF_INLINING
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = ON;
GO

-- Configuration: VERBOSE_TRUNCATION_WARNINGS
-- Current Value: ON
ALTER DATABASE SCOPED CONFIGURATION SET VERBOSE_TRUNCATION_WARNINGS = ON;
GO

-- Configuration: XTP_PROCEDURE_EXECUTION_STATISTICS
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET XTP_PROCEDURE_EXECUTION_STATISTICS = OFF;
GO

-- Configuration: XTP_QUERY_EXECUTION_STATISTICS
-- Current Value: OFF
ALTER DATABASE SCOPED CONFIGURATION SET XTP_QUERY_EXECUTION_STATISTICS = OFF;
GO


