CREATE SEARCH PROPERTY LIST [DocumentPropertyList] ;
GO
ALTER SEARCH PROPERTY LIST [DocumentPropertyList]
ADD N'Author'
WITH (PROPERTY_SET_GUID = N'f29f85e0-4ff9-1068-ab91-08002b27b3d9', PROPERTY_INT_ID = 4 , PROPERTY_DESCRIPTION = N'Document author metadata' );
GO
ALTER SEARCH PROPERTY LIST [DocumentPropertyList]
ADD N'Title'
WITH (PROPERTY_SET_GUID = N'f29f85e0-4ff9-1068-ab91-08002b27b3d9', PROPERTY_INT_ID = 2 , PROPERTY_DESCRIPTION = N'Document title metadata' );
GO
